library my_prj.globals;

bool isLoggedIn = false;
int currentPage = 1;
//var dateNow = new DateTime.now();
int days = 0;
int hours = 0;
int minutes = 0;
int secs = 0;
var eventDate = new DateTime(2020, 9, 25, 0, 0,0,0);
String homeMessage = "On behalf of the Steering Committee for the Judge Charles V. Johnson Youth and Law Forum, Thank you for joining us on Saturday September 26, 2020 for our 30th Anniversary Forum.\n Like i many years past, The Youth and Law Forum was energizing, had relevant sessions for middle and high-school aged youth and their parents/guardians. It was our first virtual, on-line forum, and it was a success!!\n\nOur theme, “The Power of One: In Each of Us a Flame”, was adopted to challenge each youth and each adult to commit to learning how to make critical differences in the areas of law and justice. There is no better time than the present for this urgent mission!\n\nPlease stay tuned to this page and links for updates on the forum and on the Founders’ Anniversary Dinner. \n\nThe Judge Charles V. Johnson Youth and Law Forum is funded in part by a Neighborhood Matching Fund Award from the Seattle Department of Neighborhoods. Please click on the link for a roster of additional current and past collaborators and supporters.\n\nRemember: It is the Power of One!\n";
String whatIsIt = "The Judge Charles V. Johnson Youth & Law Forum is a fun, interactive and free community legal education program for teens and pre-teens, parents and guardians.  It is offered annually to youth from all ethnic and diverse backgrounds. Judge The Charles V. Johnson Youth & Law Forum is an annual event first organized in 1990 by members of First AME Church. The Judge Charles V. Johnson Youth and Law Forum is a program of The MLK FAME Community Center, which is a 501(c)(3) organization. Contributions may be tax deductible, subject to tax guidelines. ";
String objectives = "To use contemporary illustrations and workshops to teach basic legal rights and responsibilities, to expose youth to and encourage their consideration of the breadth of justice system careers, and to build and maintain bridges between community youth and community justice system participants. ";
String history = "In response to deteriorating relationships between the justice system and community youth in particular, the Forum began as a First AME Church community outreach in 1990 by King County Superior Court Judge Charles V. Johnson, Ret, Judge Norma Smith Cannon, Ret, Judge LeRoy McCullough, and others.  The model has been replicated throughout the State of Washington.  It is as relevant today as it was in 1990.";